### ISSUE TITLE
ERROR: adding extensions in section default 

### ISSUE THREAD

**Issue by mox386** [OpenVPN/easy-rsa#142] opened 2017-08-24 02:45 UTC
ERROR: adding extensions in section default
140234402317984:error:22097082:X509 V3 routines:DO_EXT_NCONF:unknown extension name:v3_conf.c:124:
140234402317984:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:93:name=copy_extensions, value=copy

Easy-RSA error:

signing failed (openssl output above may have more detail)

**Comment by danhunsaker** [comment] 2017-08-24 02:53
Duplicate of #141

**Closed** 2017-08-24 03:06 UTC
