### ISSUE TITLE
sh.exe crashes on virtual Windows servers

### ISSUE THREAD

**Issue by Arno-PPS** [OpenVPN/easy-rsa#619] opened 2022-07-06 12:46 UTC
I use the OpenVPN Community Edition under Windows, since some versions Easy-RSA 3 including the MirBSD Korn Shell is included.
Unfortunately, I can not get this to work, a search on the Internet was unfortunately fruitless:

Background is the crash when simply calling sh.exe (without parameters).
In the event log you can find:
Name der fehlerhaften Anwendung: sh.exe, Version: 39.0.14.1, Zeitstempel: 0x51ce1024
Name des fehlerhaften Moduls: sh.exe, Version: 39.0.14.1, Zeitstempel: 0x51ce1024
Ausnahmecode: 0x40000015
Fehleroffset: 0x00015fc3
ID des fehlerhaften Prozesses: 0x234
Startzeit der fehlerhaften Anwendung: 0x01d8907d50e50855
Pfad der fehlerhaften Anwendung: C:\Program Files\OpenVPN\easy-rsa\bin\sh.exe
Pfad des fehlerhaften Moduls: C:\Program Files\OpenVPN\easy-rsa\bin\sh.exe
Berichtskennung: 3e059450-bdfe-47be-a74f-7e36e4f4bc7d
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

Affected are servers 2016 and 2019, which are all virtual machines (rented from Strato or Hetzner).
On an in-house server 2019 (NOT virtual) as well as on various Windows 10 computers there are no problems here.

About a tip from you, what I might have to install additional prerequisites or what else could be the problem, I would be very grateful.

**Comment by TinCanTech** [comment] 2022-07-06 13:05
Translation by goolag:
```
Faulting application name: sh.exe, version: 39.0.14.1, timestamp: 0x51ce1024
Faulting module name: sh.exe, version: 39.0.14.1, timestamp: 0x51ce1024
Exception code: 0x40000015
Error offset: 0x00015fc3
Faulting process ID: 0x234
Faulting application start time: 0x01d8907d50e50855
Faulting application path: C:\Program Files\OpenVPN\easy-rsa\bin\sh.exe
Faulting module path: C:\Program Files\OpenVPN\easy-rsa\bin\sh.exe
Report ID: 3e059450-bdfe-47be-a74f-7e36e4f4bc7d
Full name of the faulty package:
Application ID relative to the faulty package:
```

**Comment by TinCanTech** [comment] 2022-08-07 12:12
This could also be caused by a date which is beyond the 2038 cut-off for 32bit applications, in this case `date.exe`.

**Comment by TinCanTech** [comment] 2022-08-22 11:42
This project does not support `@(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $` `sh.exe`.

Closing as insolvable.

**Closed by TinCanTech** 2022-08-22 11:42 UTC
Labels: wontfix, windows, unclassified
