### ISSUE TITLE
Error generating cert using pkitool macOS

### ISSUE THREAD

**Issue by marncosta** [OpenVPN/easy-rsa#965] opened 2023-06-13 19:37 UTC
Running pki tools macOS - Tunnelbrick 3.3.8

Using Common Name: QAServer
error on line 39 of /Users/qatest/Library/Application Support/Tunnelblick/easy-rsa/libressl.cnf
8701377152:error:0EFFF068:configuration file routines:CRYPTO_internal:variable has no value:/AppleInternal/Library/BuildRoots/aaefcfd1-5c95-11ed-8734-2e32217d8374/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/crypto/conf/conf_def.c:566:line 39

**Comment by TinCanTech** [comment] 2023-06-13 19:47
Technically, this is a **TunnelBlick** error.

Easy-RSA does not create `libressl.cnf`.

I'll leave this open for reference and on the chance that the problem originates here and not from Tunnelblick.

**Comment by TinCanTech** [comment] 2023-06-13 20:10
@marncosta Can you post a copy of `libressl.cnf` here ?

**Comment by ecrist** [comment] 2023-06-13 21:16
If this is related to 2.x we won't fix it. We will fix 3.x related bugs though.

Eric F Crist
________________________________

**Comment by TinCanTech** [comment] 2023-06-13 21:45
@jkbullard Thank you for the information. If the file in use is as your template then the line in question is as follows (Line numbers added for clarity):
```
37) dir		= $KEY_DIR		# Where everything is kept
38) certs		= $dir			# Where the issued certs are kept
39) crl_dir		= $dir			# Where the issued crl are kept
```
This suggests that `$KEY_DIR` is undefined, possibly..

@ecrist This appears to be a config file for Easy-RSA v2x:
```
# libressl.cnf.template
# For use with easy-rsa version 2.0 and LibrSSL [sic]
```

@marncosta This sounds **very old and out of date**..

**Comment by TinCanTech** [comment] 2023-06-13 22:06
What ever the problem is, it is not a bug with Easy-RSA version 3.

**Closed by TinCanTech** 2023-06-13 22:06 UTC
