### ISSUE TITLE
easyrsa3 really is a "bash script" and not a "shell script"

### ISSUE THREAD

**Issue by lopter** [OpenVPN/easy-rsa#137] opened 2017-08-01 15:51 UTC
Hello,

easyrsa3 uses bash-specific features (namely `[[`), and therefore fails to execute cleanly on hosts where bash isn't the default shell (e.g. Debian/Ubuntu, OpenBSD, FreeBSD, OpenWRT…):

```
…/easyrsa3/easyrsa: 644: …/easyrsa3/easyrsa: [[: not found
```
If depending on bash is the intention then the shebang should be changed to: `#!/usr/bin/env bash`.

**Comment by uwehermann** [comment] 2017-08-17 14:49
Yup, I had the same error message. This issue seems to be a duplicate of #135, which also contains a fix to make the script more portable instead of making it bash-only.

**Comment by ecrist** [comment] 2017-08-21 22:41
I agree this is an issue (FreeBSD guy myself).  I'll work on fixing this in a future release.  The real problem is the Windows support.  Ultimately, I'd like to convert this to a C or C++ program, away from sh/bash.

**Comment by ecrist** [comment] 2017-08-23 01:14
I have not change the sh-bang, yet, due to some testing concerns, but I've merged the pull request that does away with the [[.

**Closed by ecrist** 2017-08-23 01:14 UTC
Labels: enhancement
