### ISSUE TITLE
safessl-easyrsa.cnf not found

### ISSUE THREAD

**Issue by TMTYD** [OpenVPN/easy-rsa#429] opened 2021-02-09 04:10 UTC
Hi

when I run this ./easyrsa sign-req server, the following error message appears.

```
Can't open /xxx/xxx/EasyRSA-3.0.8/pki/safessl-easyrsa.cnf for reading, No such file or directory
140245874099392:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/xxx/xxx/EasyRSA-3.0.8/pki/safessl-easyrsa.cnf','r')
140245874099392:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
Can't open /xxx/xxx/EasyRSA-3.0.8/pki/safessl-easyrsa.cnf for reading, No such file or directory
140044129301696:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/xxx/xxx/EasyRSA-3.0.8/pki/safessl-easyrsa.cnf','r')
140044129301696:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:

```
The entire directory does not contain a safessl-easyrsa.cnf file, where can I find it?

The only * .cnf file is openssl-easyrsa.cnf

**Comment by TinCanTech** [comment] 2021-02-09 16:15
Is this your first time using Easy-RSA3 or have upgraded to version 3.0.8 from an earlier release ?

**Comment by TMTYD** [comment] 2021-02-09 16:39
It's my first time using easy-rsa

**Comment by TinCanTech** [comment] 2021-02-09 17:24
How did you install Easy-RSA ?

**Comment by TMTYD** [comment] 2021-02-09 19:58
i got the easy-rsa 3.0.8 via wget and then unzipped the tgz file

**Comment by TMTYD** [comment] 2021-02-09 20:01
I found this, can I use this?
https://github.com/OpenVPN/easy-rsa/issues/363#issuecomment-614223703

**Comment by TinCanTech** [comment] 2021-02-09 20:28
Did you run `./easyrsa init-pki` first ?

**Comment by TMTYD** [comment] 2021-02-09 20:30
yes of course

**Comment by TMTYD** [comment] 2021-02-09 20:40
i found my mistake, i have this in the vars
set_var EASYRSA_SSL_CONF "$ EASYRSA / openssl-easyrsa.cnf" not commented out, after commenting out it works

**Comment by TinCanTech** [comment] 2021-02-09 21:18
Finding the cause is great.

Now I am curious why the default for `EASYRSA_SSL_CONF` does not work if specified in `vars` ?

**Comment by TMTYD** [comment] 2021-02-09 21:29
I can't tell you that, in any case, I've now commented out and it works

**Comment by Prouflon** [comment] 2021-05-02 20:32
> Now I am curious why the default for `EASYRSA_SSL_CONF` does not work if specified in `vars` ?

The [easyrsa script](https://github.com/OpenVPN/easy-rsa/blob/41a6bc6845f1e73641c8658f44dce67cd68fbb27/easyrsa3/easyrsa#L554) checks whether the file pointed to by the variable does **not** exist and only creates a safessl-easyrsa.cnf in that case.

Specifically, if you point the `EASYRSA_SSL_CONF` variable to the location of the config at `$EASYRSA/openssl-easyrsa.cnf` this:
[`if [ ! -f "$EASYRSA_SSL_CONF" ] && [ -f "$EASYRSA/openssl-easyrsa.cnf" ];`](https://github.com/OpenVPN/easy-rsa/blob/41a6bc6845f1e73641c8658f44dce67cd68fbb27/easyrsa3/easyrsa#L554)
will always evaluate to false and not create a safessl file.

Not sure if this behavior matches up with the [comment in the vars.example](https://github.com/OpenVPN/easy-rsa/blob/41a6bc6845f1e73641c8658f44dce67cd68fbb27/easyrsa3/vars.example#L195). In any case, the default value does not make sense to me. But since this option is in the advanced options section, you are probably better off leaving it alone anyways ^^

**Comment by TinCanTech** [comment] 2021-05-02 20:37
@Prouflon If you have analysed the problem and can see a solution then, perhaps, you could provide a patch ?

**Comment by Prouflon** [comment] 2021-05-02 20:43
The solution is to leave the advanced options alone, if you don't understand them.

Obviously the documentation in the vars.example is misleading to some (including me), but I wouldn't know how to rewrite it, because I don't know what that variable is actually for.

**Comment by TinCanTech** [comment] 2021-05-02 20:50
If I change `vars`:
`set_var EASYRSA_SSL_CONF	"$EASYRSA/openssl-easyrsa.cnf"`
to a valid setting and then `easyrsa` borks, who is at fault ?

Am i at fault for setting an alternate but yet valid setting or is `easyrsa` at fault for allowing me to change something which the script cannot handle correctly ?

**Comment by TinCanTech** [comment] 2021-05-02 21:11
**For The Record**:

There are numerous circumstances where `EASYRSA_SSL_CONF` simply does not work as intended.
The example above by @Prouflon is only one in a variety of others..

**Comment by Prouflon** [comment] 2021-05-03 08:07
I just found out, that the default value in the easyrsa script is actually different.
So fixing the vars.example to reflect that should protect future users from uncommenting this wrong default value.

**Comment by gatos-cc** [comment] 2021-06-24 19:06
So what is the work around here?  I had a working ovpn setup, allowed the server to apply security patches, and now I get this trying to generate new profiles:
```
Can't open ....../pki/safessl-easyrsa.cnf for reading, No such file or directory
```

I have a completely default vars file with EASYRSA_SSL_CONF commented out:
```
#set_var EASYRSA_SSL_CONF       "$EASYRSA/openssl-easyrsa.cnf"
```

But I'm not clear at all how to get rid of that error.  `openssl-easyrsa.cnf` does exist, but not `safessl-easyrsa.cnf` - I'm not clear if they're even supposed to be the same file or not.

**Comment by Prouflon** [comment] 2021-06-28 09:29
The `safessl-easyrsa.cnf` is created from the `openssl-easyrsa.cnf`, but the bash variables are replaced with their actual values.

You could try to create the file by copying and filling them in. If you know `sed`, you can have a look at [this command](https://github.com/OpenVPN/easy-rsa/blob/41a6bc6845f1e73641c8658f44dce67cd68fbb27/easyrsa3/easyrsa#L382), where the easyrsa script generates the `safessl-easyrsa.cnf`.

**Comment by TinCanTech** [comment] 2022-03-22 03:39
> The [easyrsa script](https://github.com/OpenVPN/easy-rsa/blob/41a6bc6845f1e73641c8658f44dce67cd68fbb27/easyrsa3/easyrsa#L554) checks whether the file pointed to by the variable does not exist and only creates a safessl-easyrsa.cnf in that case.

Trying to track this down, I think the problem is:
https://github.com/OpenVPN/easy-rsa/blob/381fda9a934ec32547d6548489482a5d1068df32/easyrsa3/easyrsa#L561

This needs improvement.

**Comment by Prouflon** [comment] 2022-03-22 09:53
Yeah, this block is very problematic.
If `openssl-easyrsa.cnf` is not in the directory `$EASYRSA`, the directory of the script, then nothing happens.
When installing easyrsa with a package manager, `$EASYRSA` is probably `/usr/bin`.
Either by symlink, or the easyrsa script is just there.
The `openssl-easyrsa.cnf`  usually lands in `/etc/easyrsa` or something similar.

This block can only work, if the script and the config are in the same directory (and will never work if the [current line](https://github.com/OpenVPN/easy-rsa/blob/d55e0f13bad537017b62688a0bb4e088350d9c65/easyrsa3/vars.example#L202) in vars.example is not commented out, because both if statements are mutually exclusive).

Without changing much, I would propose something like:
```
[ -f "$EASYRSA_SSL_CONF" ] && easyrsa_openssl makesafeconf  || die "$EASYRSA_SSL_CONF does not exist!"
```

**Comment by Prouflon** [comment] 2022-03-24 11:16
It might be desirable to copy the default config into newly generated `$PKI` directories.
As before, try to copy from the `$EASYRSA` base directory, but additionally search common global configuration directories (if easyrsa was not cloned directly from github, but rather installed via package manager).

I implemented the changes I would make in #502 
Do you think something like this is the way to go, or do you want to make other changes to how configuration files are handled?

**Comment by TinCanTech** [comment] 2022-03-24 16:13
Linking: #499

**Comment by TinCanTech** [comment] 2022-03-29 14:35
Please try again with `git/master`.

**Comment by TinCanTech** [comment] 2022-04-05 23:58
Closed via https://github.com/OpenVPN/easy-rsa/pull/528

Or please re-open.

**Closed by TinCanTech** 2022-04-05 23:58 UTC
Labels: BUG, feedback-requested, OpenSSL-Config
