### ISSUE TITLE
easyrsa_random failed on Windows

### ISSUE THREAD

**Issue by FreeBeing11** [OpenVPN/easy-rsa#926] opened 2023-04-04 21:24 UTC
Hi,

Since OpenVPN 2.6.0 (and EasyRSA 3.1.2), I can't setup any new OpenVPN certificates installation.
(same with OpenVPN 2.6.2)

At the beginning, with ./easyrsa init-pki

I obtain :
"Easy-RSA error:

easyrsa_random failed

Easy-RSA error:

secure_session - random_session ''

EasyRSA Version Information
Version:     3.1.2"

I tried with Windows 11 22H2, and Windows Server 2022 (21H2), but the problem is the same.

With old OpenVPN 2.5.6 (EasyRSA 3.0.8) and Server 2022, no problem.

I even tried to mix old EasyRSA 3.0.8 folder with newer OpenSSL provided by OpenVPN 2.6.2 : it works.
So, it's a EasyRSA 3.1.2 bug.

Please, how can I fix that ?

Thank you

**Comment by TinCanTech** [comment] 2023-04-04 22:04
The issue can be caused by `EASYRSA_OPENSSL` (in `vars` file) not pointing to a valid `openssl` binary.

For Windows installation the standard setting is:

    set_var EASYRSA_OPENSSL "C:/Program Files/Openvpn/bin/openssl.exe


Please verify that you have defined EASYRSA_OPENSSL correctly in `vars`.

If the fix above does not resolve the issue then I believe this problem has been fixed in [`git/master/easyrsa`](https://raw.githubusercontent.com/OpenVPN/easy-rsa/master/easyrsa3/easyrsa)

You can try that version.

**Comment by FreeBeing11** [comment] 2023-04-04 22:19
Hi,

I already set that into "vars" file, and it works with EasyRSA 3.0.8

But, with EasyRSA 3.1.2, it don't works, with the "easyrsa_random failed" error.

Thank you.

**Comment by FreeBeing11** [comment] 2023-04-05 06:47
The openssl.exe provided by OpenVPN 2.6.2 is working, and generate chars (I tried manually the rand command).

With the same "vars" and same openssl.exe, EasyRSA 3.0.8 works, but 3.1.2 not.

I tried to debug with ProcessMonitor, and it didn't find openssl.exe with EasyRSA 3.1.2
![Server 2022-2023-04-05-08-22-25](https://user-images.githubusercontent.com/129903664/230001495-b34c2e1c-df68-4cc5-a38b-84137fdcb4a9.png)

Finally, I tried your latest version of "easyrsa" script, and I have directly an error about openssl that is not found.
That's a bug, because "vars" is defined correctly, and I checked everything.
(and EasyRSA 3.0.8 works with that)

```
EasyRSA Shell
# ./easyrsa init-pki

Easy-RSA error:

* OpenSSL must either exist in your PATH
  or be defined in your vars file.

Invalid SSL output for 'version':

./easyrsa[5841]: openssl: not found

EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     undefined
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | win | @(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $ |


EasyRSA Shell
```
Screenshot of my settings provided.
![Server 2022-2023-04-05-08-44-11](https://user-images.githubusercontent.com/129903664/230002327-a120b186-ff36-499d-9c94-200528c7b830.png)


Thank you

**Comment by TinCanTech** [comment] 2023-04-05 12:02
> That's a bug, because "vars" is defined correctly, and I checked everything

With a bold statement like that you need to provide the proof.

```
**# If your OpenSSL command is not in the system PATH, you will need to define
# the path here. Normally this means a full path to the executable, otherwise
# you could have left it undefined here and the shown default would be used.
#
# Windows users, remember to use paths with forward-slashes (or escaped
# back-slashes.) Windows users should declare the full path to the openssl
# binary here if it is not in their system PATH.
#
#set_var EASYRSA_OPENSSL	"openssl"
#
# This sample is in Windows syntax -- edit it for your path if not using PATH:
#set_var EASYRSA_OPENSSL	"C:/Program Files/OpenSSL-Win32/bin/openssl.exe"
**
```
I believe that you have used `\` incorrectly.

**Comment by FreeBeing11** [comment] 2023-04-05 16:58
Same error...

I didn't use used backslash `\` only slash `/`

Also, I tried without the set_var EASYRSA_OPENSSL line, but I have the same problem.

I don't understand why everything is working with EasyRSA 3.0.8 but 3.1.2 not, with the same settings.

Screenshot taken without the set_var line, and debug with process monitor (it seems EasyRSA is blind, and can't find openssl.exe, even in registry ; we can see that into the 2 last process monitor lines).
![Server 2022-2023-04-05-18-57-15](https://user-images.githubusercontent.com/129903664/230151368-6999f681-0a96-429d-bf5a-ac45e5bfa48e.png)

**Comment by TinCanTech** [comment] 2023-04-05 17:13
We already know that EasyRSA v3.1.2 does not work for you.

I asked you to test EasyRSA v3.1.3 a.k.a. `git/master` --  **Please do so**.

Please do not post screen shots. Learn how to copy/paste text from a terminal window.

I have tested this myself **Today on Win-10** and I cannot replicate your problem.

**Comment by FreeBeing11** [comment] 2023-04-05 18:03
I have news :

The only way I found to get latest version to work is to add the OpenVPN bin folder into system PATH, manually.

Defining openssl var with EasyRSA "vars" file don't do anything.
This feature seems to be broken.
The same feature works with 3.0.8

**Comment by TinCanTech** [comment] 2023-04-05 18:24
> The only way I found to get latest version to work is to add the **OpenVPN** bin folder into system PATH, manually.

- You add `openssl` binary to the system path **not** OpenVPN.
- What **exactly** did you add to your PATH ?

Try this:
- Start EasyRSA.
- Type this in to the terminal: `openssl rand -hex 4`
- Paste the result.

**Comment by FreeBeing11** [comment] 2023-04-05 18:55
The OpenVPN "bin" directory contains openssl.exe
You didn't seen that ?

So, I added to Windows system PATH :
C:\Program Files\OpenVPN\bin

And, it works.

But, that's not normal. "vars" file with OpenSSL PATH defined must works too, like older EasyRSA versions.


Resultat of the `openssl rand -hex 4` command (it works) :

`EasyRSA Shell
# openssl rand -hex 4
86b3629f`

**Comment by TinCanTech** [comment] 2023-04-05 19:15
When `easyrsa` tells you this:
```
Easy-RSA error:

    OpenSSL must either exist in your PATH
    or be defined in your vars file.

Invalid SSL output for 'version':

./easyrsa[5841]: openssl: not found
```
it means that you have NOT defined `EASYRSA_OPENSSL` in the `vars` file.

**Comment by FreeBeing11** [comment] 2023-04-05 19:45
That's wrong, because I defined correctly EASYRSA_OPENSSL in the "vars" file.

I already shown that important thing on the 2nd screenshot.
You can check that.

Please, did you tried with the same environment, same settings, with OpenVPN 2.6.2 on Windows ?

**Comment by TinCanTech** [comment] 2023-04-05 21:58
I have successfully tested EasyRSA v3.1.2 installed with OpenVPN 2.6.2-I001 (and v3.1.3 installed manually).

Try this:
- **Use EasyRSA v3.1.3 `git/master`**
- Exit EasyRSA
- Start EasyRSA
- Type into the command line: `set`
- Post the result.
  Edit out your private information, if you prefer.

Next:
- Type into the command line: `openssl version`
- Post the result.

Then:
- Type into the command line: `./easyrsa version`
- Post the result.
 
Then:
- Type into the command line: `./easyrsa`
- Post the result.

Then:
- DO NOT USE `init-pki` first!
- Type into the command line: `./easyrsa build-ca`
- Post the result.

**Comment by FreeBeing11** [comment] 2023-04-06 07:09
Hi,

I extracted again latest EasyRSA from git/master, and run EasyRSA-Start.bat :

**set**
`PATH='C:/Program Files/OpenVPN/easy-rsa;C:/Program Files/OpenVPN/easy-rsa/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Administrateur\AppData\Local\Microsoft\WindowsApps;'`

I also defined "vars" file correctly :
set_var EASYRSA_OPENSSL	"C:/Program Files/OpenVPN/bin/openssl.exe"

**openssl version**
`bin/sh: openssl: not found`

That's normal, because "C:/Program Files/OpenVPN/bin" is not into the PATH (and it was not needed into previous EasyRSA 3.0.8, only EASYRSA_OPENSSL	path).


**./easyrsa version**

```
Easy-RSA error:

* OpenSSL must either exist in your PATH
  or be defined in your vars file.

Invalid SSL output for 'version':

./easyrsa[5841]: openssl: not found

EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     undefined
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | win | @(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $ |
```


**./easyrsa**

```
Easy-RSA error:

* OpenSSL must either exist in your PATH
  or be defined in your vars file.

Invalid SSL output for 'version':

./easyrsa[5841]: openssl: not found

EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     undefined
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | win | @(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $ |
```


**./easyrsa build-ca**
```
* Using Easy-RSA configuration:
  C:/Program Files/OpenVPN/easy-rsa/vars

Easy-RSA error:

EASYRSA_PKI does not exist (perhaps you need to run init-pki)?
Expected to find the EASYRSA_PKI at: C:/Program Files/OpenVPN/easy-rsa/pki
Run easyrsa without commands for usage and command help.

EasyRSA Version Information
Version:     ~VER~
Generated:   ~DATE~
SSL Lib:     OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)
Git Commit:  ~GITHEAD~
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: dev | win | @(#)MIRBSD KSH R39-w32-beta14 $Date: 2013/06/28 21:28:57 $ |
```

The latest error is normal, because init-pki was not run.

Note : you can see that many commands don't see "vars" file, but build-ca yes.

Note 2 : I will try to explain you step by step how to reproduce the OpenVPN 2.6.2 problem with EasyRSA, on a fresh Windows installation (without OpenSSL installed, just use OpenSSL provided by OpenVPN).

**Comment by FreeBeing11** [comment] 2023-04-06 07:15
How to reproduce the bug (I tried on a 3rd system), on Windows 10 22H2, Windows 11 22H2, and Server 2022 21H2 :

- Fresh install of Windows, without any OpenSSL installed.
- Install OpenVPN 2.6.2 with OpenSSL and EasyRSA 3.1.2 enabled with MSI installer.
- Copy C:\Program Files\OpenVPN\easy-rsa\vars.example to C:\Program Files\OpenVPN\easy-rsa\vars
- Define OpenSSL var into "vars" file, like this :
**set_var EASYRSA_OPENSSL "C:/Program Files/OpenVPN/bin/openssl.exe"**
- Run EasyRSA-Start.bat
- Using any easyrsa command don't work, because openssl is not found.

Do exactly the same thing with older OpenVPN (2.5.6, for example) that provided EasyRSA 3.0.8 : everything works.

Also, I noticed EasyRSA-Start.bat provided by OpenVPN 2.6.2 try to get good OpenVPN/bin PATH into the registry :
`@echo OFF
rem Automatically set PATH to openssl.exe
FOR /F "tokens=2*" %%a IN ('REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN" /ve') DO set "PATH=%PATH%;%%b\bin"
bin\sh.exe bin\easyrsa-shell-init.sh`

But, the result is not good, because **set** command gives for PATH :
`PATH='C:/Program Files/OpenVPN/easy-rsa;C:/Program Files/OpenVPN/easy-rsa/bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\Maxime\AppData\Local\Microsoft\WindowsApps;REG_SZ    C:\Program Files\OpenVPN\\bin'`

(see the end **REG_SZ    C:\Program Files\OpenVPN\\bin**) the PATH is broken and mixed with a name of registry value.

**Comment by FreeBeing11** [comment] 2023-04-06 07:20
I changed the defect EasyRSA-Start.bat to that, to get EasyRSA 3.1.2 and later works :
`@echo OFF
rem Automatically set PATH to openssl.exe
set "PATH=%PATH%;C:\Program Files\OpenVPN\bin"
bin\sh.exe bin\easyrsa-shell-init.sh
`

So, there are 2 bugs :
- EasyRSA-Start.bat that do not retrieve correctly the OpenVPN/bin (that contains openssl.exe) correctly to add to the PATH
- "vars" file that is not read correctly, even with OpenSSL path defined.

**Comment by TinCanTech** [comment] 2023-04-06 12:38
@FreeBeing11 Thank you for you detailed analysis.

While I cannot replicate the problem you have described, I can see and understand what is going wrong: `$PATH` is being set incorrectly, apparently.

Please try this; Open a standard command prompt and enter this:
```
/F "tokens=2*" %a IN ('REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN" /ve') DO echo KEY: %b
```
Paste the result.

**Comment by TinCanTech** [comment] 2023-04-06 21:47
This appears to be an OpenVPN packaging problem.

The EasyRSA version of [`EasyRSA-Start.bat`](https://raw.githubusercontent.com/OpenVPN/easy-rsa/master/distro/windows/EasyRSA-Start.bat) does not try to set the `PATH`.

Leaving this open for further discussion of this **identified** issue.

**Comment by FreeBeing11** [comment] 2023-04-06 21:54
Ok... but, it don't solve the other bug.

This setting into "vars" don't works with latest version of EasyRSA, but "old" 3.0.8 yes :

set_var EASYRSA_OPENSSL "C:/Program Files/OpenVPN/bin/openssl.exe"

So, to workaround, I have to set system PATH to "C:/Program Files/OpenVPN/bin" or set PATH into EasyRSA-Start.bat directly.

How can we fix it, please ?

**Comment by TinCanTech** [comment] 2023-04-06 22:24
Please use your _work-around_ for the time being.

With your feedback, we have identified a bug.

**Comment by FreeBeing11** [comment] 2023-04-07 05:58
Thank you for your help.

That's OK for me.

**Comment by TinCanTech** [comment] 2023-04-10 17:58
Moved-to: https://github.com/OpenVPN/openvpn-build/issues/352

**Closed by TinCanTech** 2023-04-10 17:58 UTC
Labels: BUG, openvpn, packaging, windows, Priority, Community reveiwed, Version 3.1.x

**Comment by cocainumusys** [comment] 2024-01-29 09:38
**If someone has constant errors with SSL paths, transfer the file openssl.exe** (with all _openssl_ *_.dll_ **libraries**)  from _C:\Program Files\OpenVPN\bin_ in _C:\Program Files\OpenVPN\easy-rsa\bin_ > **apply a global patch (you can also use vars).** **Thanks for your attention**
