### ISSUE TITLE
vars.bat on Windows - "reg query" change

### ISSUE THREAD

**Issue by morrisalex** [OpenVPN/easy-rsa#157] opened 2017-10-13 11:24 UTC
Apologies if this has already been spotted - I've tried searching for this but without success.

I have tested this on both Windows 7 Enterprise x64 and Windows 10 Pro x64. I don't know if the same behaviour occurs in other versions of Windows. Other people with other versions of Windows may be able to test and verify.

I'm using the version of easy-rsa which was bundled with OpenVPN v2.4.4, installed by default into C:\Program Files\OpenVPN.

The vars.bat.sample script contains this line:
`FOR /F "tokens=2*" %%a IN ('REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN"') DO set "PATH=%PATH%;%%b\bin"`

The important bit of that line - the REG QUERY command - returns the contents of the entire key:
```
reg query "hkey_local_machine\software\openvpn"

HKEY_LOCAL_MACHINE\software\openvpn
    config_dir    REG_SZ    C:\Program Files\OpenVPN\config
    config_ext    REG_SZ    ovpn
    exe_path    REG_SZ    C:\Program Files\OpenVPN\bin\openvpn.exe
    log_dir    REG_SZ    C:\Program Files\OpenVPN\log
    priority    REG_SZ    NORMAL_PRIORITY_CLASS
    log_append    REG_SZ    0
    (Default)    REG_SZ    C:\Program Files\OpenVPN
    disable_save_passwords    REG_DWORD    0x0
    ovpn_admin_group    REG_SZ    OpenVPN Administrators
```

As a result, the variable %%b is set to the final result of the REG QUERY command, i.e. "OpenVPN Administrators", and the PATH environment variable then ends with "';OpenVPN Administrators\bin", which doesn't find the openssl.exe binary.

Instead, the variable %%b should be set to the (Default) value of the key: "C:\Program Files\OpenVPN".

The REG QUERY command supports the switch "/ve" to restrict the result to the (Default) value:
```
reg query "hkey_local_machine\software\openvpn" /ve

HKEY_LOCAL_MACHINE\software\openvpn
    (Default)    REG_SZ    C:\Program Files\OpenVPN
```

As noted above, this appears to apply to W7 Ent x64 and W10 Pro x64; I can't comment for other versions.

**Comment by TinCanTech** [comment] 2017-10-14 16:45
> As a result, the variable %%b is set to the final result of the REG QUERY command, i.e. "OpenVPN Administrators", and the PATH environment variable then ends with "';OpenVPN Administrators\bin", which doesn't find the openssl.exe binary.

I have tested this on Win10Prox64 and my results do not match yours. `c:\Path_to\openvpn\bin` is appended to my PATH.

However, I can confirm that the `/ve` switch does only return the value required.
EG: vars.bat:
`FOR /F "tokens=2*" %%a IN ('REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\OpenVPN" /ve') DO echo "%%b"` 
Returns **only** `c:\path_to\openvpn`

On a side note: This solution is a little crude because every time vars.bat is invoked the openvpn binary path is again appended to PATH, resulting in:
`PATH=$Current_path;C:\Program Files\OpenVPN\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\OpenVPN\bin; ... etc`

**Comment by kyanha** [comment] 2018-12-24 10:52
OP's situation occurs when one deletes a value in the registry key, and then manually recreates it.

**Comment by kyanha** [comment] 2018-12-24 11:40
However, I can't find anywhere (either in this repo or in the main OpenVPN code) that has or creates vars.bat.sample, so I can't figure out where to make this change. :(

**Comment by ecrist** [comment] 2018-12-25 21:15
We do not have a vars.bat on Windows in EasyRSA 3.x.  This is something that needs to be addressed in the 2.x codebase and I don't see that happening.

**Comment by TinCanTech** [comment] 2020-01-11 04:53
Better to `upgrade` to Easyrsa v3 .. now with upgrade powers
https://github.com/OpenVPN/easy-rsa/commit/07ec923be13d45d1592e93f08a0157dbc7ed3b4c

**Comment by ecrist** [comment] 2020-01-12 02:15
Closing this; we aren't going to fix it.

**Closed by ecrist** 2020-01-12 02:15 UTC
Labels: good first issue, v2.x
