### ISSUE TITLE
Unknown extension name on Arch Linux with openssl-1.1.x and openssl-1.0.x

### ISSUE THREAD

**Issue by chaserhkj** [OpenVPN/easy-rsa#141] opened 2017-08-23 15:02 UTC
```
 $ ./easyrsa build-client-full test-cli nopass

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
..................................................+++
...........................+++
writing new private key to '/home/hkj/PKICA/easyrsa3/pki/private/test-cli.key.QU8ezJveTK'
-----
rand: Use -help for summary.
Using configuration from ./openssl-1.0.cnf
Enter pass phrase for /home/hkj/PKICA/easyrsa3/pki/private/ca.key:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'test-cli'
ERROR: adding extensions in section default
140426772926784:error:22097082:X509 V3 routines:do_ext_nconf:unknown extension name:crypto/x509v3/v3_conf.c:78:
140426772926784:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:crypto/x509v3/v3_conf.c:47:name=copy_extensions, value=copy

Easy-RSA error:

signing failed (openssl output above may have more detail)
```

On Arch Linux with openssl 1.1.0.f-2

**Comment by chaserhkj** [comment] 2017-08-23 15:06
Using openssl 1.0.2.l gives nearly the same error output:

```
 $ ./easyrsa build-client-full test-client nopass

Note: using Easy-RSA configuration from: ./vars
Generating a 2048 bit RSA private key
............+++
........................................................................................................+++
writing new private key to '/home/hkj/PKICA/easyrsa3/pki/private/test-client.key.qHXXinsj4d'
-----
Usage: rand [options] num
where options are
-out file             - write to file
-engine e             - use engine e, possibly a hardware device.
-rand file:file:... - seed PRNG from files
-base64               - base64 encode output
-hex                  - hex encode output
Using configuration from ./openssl-1.0.cnf
Enter pass phrase for /home/hkj/PKICA/easyrsa3/pki/private/ca.key:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'test-client'
ERROR: adding extensions in section default
139687761824472:error:22097082:X509 V3 routines:DO_EXT_NCONF:unknown extension name:v3_conf.c:125:
139687761824472:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=copy_extensions, value=copy

Easy-RSA error:

signing failed (openssl output above may have more detail)
```

**Comment by danhunsaker** [comment] 2017-08-23 15:12
Looks like that directive isn't valid in that section of your config. Might want to look at that.

**Comment by ecrist** [comment] 2017-08-23 17:55
I think I broke it. Is this using the v3.0.3 release?


Eric Crist

**Comment by mox386** [comment] 2017-08-24 03:19
Apologies on the duplicate issue post

Confirming that checking out 4ba461d made it work.

**Comment by ecrist** [comment] 2017-08-24 05:04
So to clarify, v3.0.3 works?

Eric Crist

**Comment by chaserhkj** [comment] 2017-08-28 14:02
Sorry for the late reply, was focused on work last week.

@danhunsaker As you may already noticed I've been using the configuration from the repo that's completely unmodified.

@ecrist Yes, I could confirm that v3.0.3 works, so there's some commit after that breaking it.

**Comment by djsly** [comment] 2017-09-01 16:55
Note that 3.0.3 is in fact a copy of 3.0.2 the binary in the tarball was not updated it seems.

**Comment by ecrist** [comment] 2017-09-02 13:33
It is not a copy, there were changes, look at the commit log. 

Eric Crist

**Comment by ecrist** [comment] 2017-09-02 14:42
Can you see if your problem is fixed in a675fc9?

**Comment by hilt86** [comment] 2017-09-04 02:56
3.0.3 does not work - at least when generating an intermediate CA.

I had to check out 4ba461d and add the change from 243f729a776c0d7bcfe5afa84c4d309100d7a397 aka ```"$EASYRSA_OPENSSL" rand -hex -out "$EASYRSA_PKI/serial" 16```

**Comment by ecrist** [comment] 2017-09-04 05:08
Can you describe every step up to the failure?

Eric Crist

**Comment by hilt86** [comment] 2017-09-07 12:37
Steps to reproduce (from memory as I re-installed the machines after generating the keys) : 

Intermediate CA CSR was created using Hashicorp Vault

-  for rootca 
- edit vars 

rootca
- run ./easyrsa init-pki 
- run ./easyrsa build-ca
- import request for intermediate CA (imca.req)
- run ./easyrsa sign-req ca imca

**Comment by ecrist** [comment] 2018-01-21 17:38
I have confirmed that I was able to successfully create an ICA with v3.0.4 and v3.0.5 (working):

`ecrist@meow:~/easy-rsa/easyrsa3-> openssl req -newkey rsa:2048 -out foo.req
Generating a 2048 bit RSA private key
........+++
........................+++
writing new private key to 'privkey.pem'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:
State or Province Name (full name) [Some-State]:
Locality Name (eg, city) []:
Organization Name (eg, company) [Internet Widgits Pty Ltd]:
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:YOUR name
Email Address []:

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
ecrist@meow:~/easy-rsa/easyrsa3-> ./easyrsa import-req foo.req ica

The request has been successfully imported with a short name of: ica
You may now use this name to perform signing operations on this request.

ecrist@meow:~/easy-rsa/easyrsa3-> ./easyrsa sign-req ca ica


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a ca certificate for 3650 days:

subject=
    countryName               = AU
    stateOrProvinceName       = Some-State
    organizationName          = Internet Widgits Pty Ltd
    commonName                = YOUR name


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from ./openssl-easyrsa.cnf
Enter pass phrase for /Users/ecrist/easy-rsa/easyrsa3/pki/private/ca.key:
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
countryName           :PRINTABLE:'AU'
stateOrProvinceName   :PRINTABLE:'Some-State'
organizationName      :PRINTABLE:'Internet Widgits Pty Ltd'
commonName            :PRINTABLE:'YOUR name'
Certificate is to be certified until Jan 19 17:36:54 2028 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Certificate created at: /Users/ecrist/easy-rsa/easyrsa3/pki/issued/ica.crt

ecrist@meow:~/easy-rsa/easyrsa3-> openssl x509 -noout -text -in pki/i
index.txt       index.txt.attr  index.txt.old   issued/         
ecrist@meow:~/easy-rsa/easyrsa3-> openssl x509 -noout -text -in pki/issued/ica.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            51:57:bc:9c:ba:b3:69:6b:e2:40:20:c4:15:ab:f2:40
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Easy-RSA CA
        Validity
            Not Before: Jan 21 17:36:54 2018 GMT
            Not After : Jan 19 17:36:54 2028 GMT
        Subject: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd, CN=YOUR name
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
            RSA Public Key: (2048 bit)
                Modulus (2048 bit):
                    00:b2:8e:da:78:e5:1b:33:7d:fe:71:7a:51:79:13:
                    61:66:4d:d7:b4:73:50:29:1e:45:a9:ef:fc:03:7a:
                    44:4a:0c:0d:5e:83:1c:65:57:f4:53:b4:36:cf:40:
                    22:34:f2:ff:4e:80:7b:e3:e8:ec:d3:9c:cd:b1:93:
                    21:60:2e:63:a4:46:af:d8:a9:bf:6b:24:0a:3a:d7:
                    c1:ca:6b:73:5f:c7:5f:48:2f:a4:11:28:4d:b2:ba:
                    ca:9f:86:af:5d:e5:4f:df:39:c0:e0:eb:da:c3:4b:
                    56:d1:da:95:ee:43:8a:ad:31:b9:20:c3:b9:e5:83:
                    4f:fa:39:43:b9:6c:12:75:c1:2b:af:30:0a:ef:9e:
                    c7:fb:0c:64:41:fb:88:0f:a5:e9:aa:50:64:c3:14:
                    20:a9:ed:79:c4:ca:1b:51:69:17:08:c7:64:16:52:
                    27:8c:2a:6e:96:98:18:ef:21:09:b9:a9:6a:24:25:
                    f4:17:cf:2c:3e:15:22:e5:4d:5e:b8:dd:e4:1b:47:
                    db:b8:75:32:1c:f6:ee:cb:e8:08:a0:cc:ec:e3:62:
                    8d:05:72:e4:a7:5f:22:2d:28:4e:f2:3d:9d:61:19:
                    f1:e6:c2:4e:79:68:06:3f:f4:60:96:58:66:73:22:
                    99:99:8d:d7:e5:b1:fa:1c:38:a5:ba:8a:41:bb:eb:
                    df:8d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Subject Key Identifier: 
                13:33:C1:F5:83:7F:95:34:57:16:2B:B9:20:0D:F1:8A:10:C4:5E:84
            X509v3 Authority Key Identifier: 
                keyid:65:48:62:F5:1E:D4:96:F8:E1:78:E1:C2:91:A6:3F:D7:CC:0E:5D:FB
                DirName:/CN=Easy-RSA CA
                serial:EC:FF:26:C5:55:DB:59:F3

            X509v3 Key Usage: 
                Certificate Sign, CRL Sign
    Signature Algorithm: sha256WithRSAEncryption
        57:db:ea:cc:7d:91:f8:05:9d:99:7d:4a:da:36:e7:3a:3d:e9:
        2e:ff:45:b9:94:fa:d9:fd:27:30:35:97:bb:b7:e4:56:a3:5d:
        dd:d8:f9:40:21:59:3e:4e:a9:28:2b:31:b6:51:76:94:ff:82:
        6c:bb:35:93:16:06:f4:b6:8d:3e
`

**Closed** 2018-01-21 17:39 UTC

**Comment by tomasz-lasko** [comment] 2018-05-30 10:15
I still have a similar problem on my Ubuntu 18.04 LTS with OpenSSL 1.1.0g:

When I want a) multiple SANs (comma delimited) or b) IP (not DNS) SAN given under --subject-alt-name=, then:

**1)** `easyrsa --subject-alt-name=IP:1.2.3.4 build-server-full 1.2.3.4` -> works, 
**2)** but when using gen-req with similar parameters (`easyrsa --subject-alt-name=IP:1.2.3.4 gen-req 1.2.3.4`)  

which works by itself

and **2a)** after that **sign-req with --copy-ext fails**, 

i.e. `easyrsa --copy-ext sign-req NAME` fails with:
`ERROR: adding extensions in section default
140305501856192:error:22097082:X509 V3 routines:do_ext_nconf:unknown extension name:../crypto/x509v3/v3_conf.c:78:
140305501856192:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:../crypto/x509v3/v3_conf.c:47:name=copy_extensions, value=copy`

however **2b)** after that **sign-req with repeated --subject-alt-name succeeds**.
i.e. `easyrsa --subject-alt-name=IP:1.2.3.4 gen-req 1.2.3.4` success ("Write out database with 1 new entries")

**Comment by ecrist** [comment] 2018-07-27 12:56
tomasz-lasko - please create a separate issue for this.
