### ISSUE TITLE
The copy of openssl-easyrsa.cnf in use does not support X509-type 'ca'

### ISSUE THREAD

**Issue by Nyr** [OpenVPN/easy-rsa#725] opened 2022-10-13 12:06 UTC
Bug in the latest v3.1.1 release:

```
./easyrsa --batch build-ca

Easy-RSA error:

The copy of openssl-easyrsa.cnf in use does not support X509-type 'ca'.
* /etc/openvpn/server/easy-rsa/pki/openssl-easyrsa.cnf
Please update openssl-easyrsa.cnf to the latest official release.

EasyRSA Version Information
Version:     3.1.1
Generated:   Thu Oct 13 06:37:48 CDT 2022
SSL Lib:     OpenSSL 1.1.1n  15 Mar 2022
Git Commit:  2083fb29b512c5b2fccf65db8e5f89771fbf90f5
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: 3.1.1 | nix | Linux | /bin/bash | OpenSSL 1.1.1n  15 Mar 2022
```

**Comment by TinCanTech** [comment] 2022-10-13 12:14
@Nyr

The problem here is caused by:
https://github.com/OpenVPN/easy-rsa/blob/2083fb29b512c5b2fccf65db8e5f89771fbf90f5/easyrsa3/easyrsa#L1318-L1324

You need to update your copy of `openssl-easyrsa.cnf`.

**Comment by Nyr** [comment] 2022-10-13 12:35
I am using the `openssl-easyrsa.cnf` built with the latest release, something is going on:

```
root@localhost:~# tar xzf EasyRSA-3.1.1.tgz
root@localhost:~# cd EasyRSA-3.1.1/
root@localhost:~/EasyRSA-3.1.1# ./easyrsa init-pki

Notice
------
'init-pki' complete; you may now create a CA or requests.

Your newly created PKI dir is:
* /root/EasyRSA-3.1.1/pki

* Using Easy-RSA configuration:

* IMPORTANT: Easy-RSA 'vars' template file has been created in your new PKI.
             Edit this 'vars' file to customise the settings for your PKI.

* Using x509-types directory: /root/EasyRSA-3.1.1/x509-types

root@localhost:~/EasyRSA-3.1.1# ./easyrsa --batch build-ca nopass

Easy-RSA error:

The copy of openssl-easyrsa.cnf in use does not support X509-type 'ca'.
* /root/EasyRSA-3.1.1/pki/openssl-easyrsa.cnf
Please update openssl-easyrsa.cnf to the latest official release.

EasyRSA Version Information
Version:     3.1.1
Generated:   Thu Oct 13 06:37:48 CDT 2022
SSL Lib:     OpenSSL 1.1.1n  15 Mar 2022
Git Commit:  2083fb29b512c5b2fccf65db8e5f89771fbf90f5
Source Repo: https://github.com/OpenVPN/easy-rsa
Host: 3.1.1 | nix | Linux | /bin/bash | OpenSSL 1.1.1n  15 Mar 2022
```

Meanwhile, in a different system, same release, it is fine:

```
nyr@DESKTOP-3V4BVLV:~$ tar xzf EasyRSA-3.1.1.tgz
nyr@DESKTOP-3V4BVLV:~$ cd EasyRSA-3.1.1
nyr@DESKTOP-3V4BVLV:~/EasyRSA-3.1.1$ ./easyrsa init-pki

Notice
------
'init-pki' complete; you may now create a CA or requests.

Your newly created PKI dir is:
* /home/nyr/EasyRSA-3.1.1/pki

* Using Easy-RSA configuration:

* IMPORTANT: Easy-RSA 'vars' template file has been created in your new PKI.
             Edit this 'vars' file to customise the settings for your PKI.

* Using x509-types directory: /home/nyr/EasyRSA-3.1.1/x509-types

nyr@DESKTOP-3V4BVLV:~/EasyRSA-3.1.1$ ./easyrsa --batch build-ca nopass
........+++++
..........+++++
nyr@DESKTOP-3V4BVLV:~/EasyRSA-3.1.1$ ./easyrsa --version
EasyRSA Version Information
Version:     3.1.1
Generated:   Thu Oct 13 06:37:48 CDT 2022
SSL Lib:     OpenSSL 1.1.1n  15 Mar 2022
Git Commit:  2083fb29b512c5b2fccf65db8e5f89771fbf90f5
Source Repo: https://github.com/OpenVPN/easy-rsa
```

I will troubleshoot later as I do not have time right now, but I suspect there is a bug with the latest release. I am definitively not using an old configuration file.

**Comment by TinCanTech** [comment] 2022-10-13 12:41
Thanks for the extra details, I am testing.

**Comment by TinCanTech** [comment] 2022-10-13 12:53
Sorry. I cannot replicate the issue here.

My first guess would be that you follow development here quite closely and so you have already tested the new `data-dir` locations, such as `/usr/local/share/easy-rsa`.  If so then perhaps the script picked up an old copy from such a place.

**Comment by Nyr** [comment] 2022-10-13 12:57
This issue is happening on a 100% clean system.

To be specific it happens in a clean Debían 11 image at Linode, while it does not happen in my also clean Debían 11 WSL image.

I will take a look later, but this is absolutely on a clean, just installed system.

**Comment by TinCanTech** [comment] 2022-10-13 13:04
> To be specific it happens in a clean Debían 11 image at Linode

Then perhaps Linode have the same issue.  They may have an old version of easyrsa installed by default.

**Comment by TinCanTech** [comment] 2022-10-13 13:07
I could have made the check above only issue a warning but I would prefer to see all old `openssl-easyrsa.cnf` replaced. Even at this level of inconvenience.

**Comment by TinCanTech** [comment] 2022-10-13 13:10
This could be related to and even fixed by #723

**Comment by TinCanTech** [comment] 2022-10-13 13:54
@Nyr Thanks to your feedback, I have just pushed a change to Easy-RSA unit-test which will allow it to be run on the downloaded/extracted release tar-ball.

Download [easyrsa-unit-tests.sh](https://raw.githubusercontent.com/OpenVPN/easyrsa-unit-tests/master/easyrsa-unit-tests.sh) to the extracted EasyRSA-xxx directory and run it from there. `./easyrsa-unit-tests.sh -v`

**Comment by Nyr** [comment] 2022-10-13 18:09
First of all, sorry for wasting your time on this, I should have troubleshooted more before opening an issue.

The problem was occurring for systems which had the `easy-rsa` package installed. Those systems were clean other than an `apt-get install openvpn`, but I was unaware that the `easy-rsa` was still among the "recommends" for the `openvpn` package. I was under the assumption that this was no longer the case and I did not check, very sorry about that.

So the issue is indeed related to the new `data-dir` locations. This is not a technical issue but I think it is an UX issue, as people doing an `apt-get install openvpn` will run into it.

One can of course do `--no-install-recommends` (as I will), but the average user will run into this.

**Comment by Nyr** [comment] 2022-10-13 18:18
Main thing which contributed to the confusion is that the `easy-rsa` package is a "recommend" in Debian, but only a "suggest" in Ubuntu.

**Comment by TinCanTech** [comment] 2022-10-13 18:23
@Nyr Thank you for your help.

This is entirely my fault for over-looking such an obvious use case.

I am re-opening this issue for better visibility.

**Comment by TinCanTech** [comment] 2022-10-13 18:45
For the record, I am drawing Easy-RSA toward the more Unix style use of separating application from data-in and output files.  However, due to Windows support, the old method has to continue to work.

The combination of having the OpenVPN install _include_ EasyRSA, plus data-in files found in the wrong order, plus making the error fatal is just a step too far. 

It is unfortunate but I may have _shot myself in the foot_ here..

**Comment by Nyr** [comment] 2022-10-13 19:12
It is not a fast nor guaranteed approach, but if the Debian package is the only one from the main distros recommending `easy-rsa` (I have not thoroughly, but it seems to be) you could potentially talk with the maintainers about a change.

Additional information within the error message could also help, but will probably not be enough for inexperienced users.

**Comment by TinCanTech** [comment] 2022-10-13 19:20
I've adjusted the EasyRSA timeline to push an **early** bug-fix out for this specific issue.

@Nyr  Again, thank you for your help. And timely reminder to test more thoroughly `;-)`.

Regarding Debian, this feels like my error not theirs.
Regarding the error message and even improving it, I agree that it would not be enough.

My initial approach was a _shade_ too severe, on this occasion.

**Comment by TinCanTech** [comment] 2022-10-16 22:39
The _work-around_ above is **not** a solution.

The solution is #727

**Closed** 2022-10-18 18:46 UTC
Labels: BUG, packaging, OpenSSL-Config, Version 3.1.x

**Comment by TinCanTech** [comment] 2022-12-08 22:37
@xinthose if you can outline the problem then this issue can be reopened.
