### ISSUE TITLE
Cannot open file:crypto/rand/randfile.c:88:Filename=/root/easy-rsa/pki/.rnd

### ISSUE THREAD

**Issue by aix4c** [OpenVPN/easy-rsa#263] opened 2018-11-04 17:07 UTC
Steps to reproduce:
easyrsa init-pki
easyrsa build-ca nopass
Can't load /root/easy-rsa/pki/.rnd into RNG
139869350920704:error:2406F079:random number generator:RAND_load_file:Cannot open file:crypto/rand/randfile.c:88:Filename=/root/easy-rsa/pki/.rnd
You are about to be asked to enter information that will be incorporated
into your certificate request.

**Comment by ecrist** [comment] 2018-12-17 02:10
Duplicate of #261

**Closed by ecrist** 2018-12-17 02:10 UTC
