### ISSUE TITLE
EASYRSA_KEY_SIZE in vars is ignored

### ISSUE THREAD

**Issue by brainpower** [OpenVPN/easy-rsa#111] opened 2016-10-26 12:33 UTC
I've set the key size to 4096 in the vars file

```
$ grep KEY_SIZE vars 
set_var EASYRSA_KEY_SIZE        4096
```

but when initializing the CA, it still uses the default 2048bit for the key:

```
$ easyrsa build-ca          
Generating a 2048 bit RSA private key
[....]
```

And yes, the vars file is inside the $PWD.

**Comment by bts368** [comment] 2016-12-12 01:15
confirming.

```
[root@g bdisk]# grep KEY vars
set_var EASYRSA_KEY_SIZE        4096
[root@g bdisk]# easyrsa init-pki && yes '' | easyrsa build-ca nopass

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /etc/openvpn/servers/keygen/bdisk/pki

Generating a 2048 bit RSA private key
...+++
.............+++
writing new private key to '/etc/openvpn/servers/keygen/bdisk/pki/private/ca.key.Orh3ijGp3Z'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:
CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/etc/openvpn/servers/keygen/bdisk/pki/ca.crt

[root@g bdisk]# openssl rsa -in pki/private/ca.key -noout -text | head -n1
Private-Key: (2048 bit)
```

Further, it never acknowledges the change in SHA either:

```
[root@g bdisk]# grep DIGEST vars
set_var EASYRSA_DIGEST          "sha512"
[root@g bdisk]# openssl x509 -in pki/ca.crt -noout -text | grep 'Signature Algorithm'
    Signature Algorithm: sha256WithRSAEncryption
    Signature Algorithm: sha256WithRSAEncryption
```

For a project that aims to aid in security, this is extremely disheartening.

**Comment by bts368** [comment] 2016-12-12 01:31
a bug in their Trac has been filed:

https://community.openvpn.net/openvpn/ticket/788

**Comment by bts368** [comment] 2016-12-12 01:44
for what it's worth, after examining the easyrsa script, it seems it's preferring flags over the vars file instead of arranging a sort of priority system between defaults|vars|cmdline args.

which the documentation/vars file does not reflect.
```

easyrsa init-pki --keysize=4096 --digest=sha512
easyrsa --keysize=4096 --digest=sha512 build-ca nopass
```
DOES, in fact, create the desired PKI. so it looks like it may ignore the vars file entirely, and relies on the commandline switches instead:

```
[root@g bdisk]# openssl rsa -in pki/private/ca.key -noout -text | head -n1                                                                                                                                         
Private-Key: (4096 bit)
[root@g bdisk]# openssl x509 -in pki/ca.crt -noout -text | grep 'Signature Algorithm'                                                                                                                              
    Signature Algorithm: sha512WithRSAEncryption
    Signature Algorithm: sha512WithRSAEncryption
```

hope this helps you.

**Comment by ecrist** [comment] 2016-12-13 23:15
Thanks for the report.  At some point in 2017 I plan on spending time going through these types of issues.

**Comment by Koleon** [comment] 2017-02-20 11:37
Hello guys, 

I have the same experience - it seems like all 'set_var' in 'vars' file are ignored. It's not just "set_var EASYRSA_KEY_SIZE" related but even: set_var EASYRSA; set_var EASYRSA_DN "cn_only"; set_var EASYRSA_ALGO; set_var EASYRSA_CURVE; set_var EASYRSA_CA_EXPIRE do not work for me.

Please check it out.

**Comment by deep-42-thought** [comment] 2017-02-20 12:32
> And yes, the vars file is inside the $PWD.

This is not enough. See #119 .

regards,
deep-42-thought

**Comment by ecrist** [comment] 2017-09-02 14:57
Is this still a problem for you in master?

**Comment by Antagonym** [comment] 2018-01-31 13:45
It would seem that EasyRSA simply does not specify any keysize at all when generating the key for the root certificate:

    L487: "$EASYRSA_OPENSSL" genrsa -aes256 -out "$out_key_tmp" -passout file:"$out_key_pass_tmp

A simple fix would be adding the keysize to the command like this:

    L487: "$EASYRSA_OPENSSL" genrsa -aes256 -out "$out_key_tmp" -passout file:"$out_key_pass_tmp" $EASYRSA_KEY_SIZE

(Adding `-config $EASYRSA_SSL_CONF` instead causes an error message to appear: `genrsa: Unknown cipher config`)

The reason this only affects the root certificate is that EasyRSA generates the key for if separately and then generates a CSR from that. When generating a regular certificate, however, the key generation is "combined into" the CSR generation:

    L586: "$EASYRSA_OPENSSL" req -utf8 -new -newkey "$EASYRSA_ALGO":"$EASYRSA_ALGO_PARAMS" \
    L587:        -config "$EASYRSA_SSL_CONF" -keyout "$key_out_tmp" -out "$req_out_tmp" $opts \
    L588:        || die "Failed to generate request"

Note the `newkey "$EASYRSA_ALGO:$EASYRSA_ALGO_PARAMS"` parameter here.

**Comment by ecrist** [comment] 2020-04-15 14:21
Possibly related to #363.  Work is being done in that ticket.

**Comment by andrew-phi** [comment] 2020-04-18 11:04
Bug present in current release 3.0.7.
Spent hours finding out what's wrong.

**Comment by ecrist** [comment] 2020-04-18 13:45
Sweet.  So, what's wrong?

**Comment by brainpower** [comment] 2020-04-18 14:09
well, vars get sourced here: https://github.com/OpenVPN/easy-rsa/blob/master/easyrsa3/easyrsa#L1694

the defaults being set below seem to overwrite what is set in vars.
Fix should be as simple as sourcing the vars *after* setting defaults or make the defaults not overwirte already set variables

**Comment by ecrist** [comment] 2020-09-09 20:11
I've done some digging, and I don't think this is a problem in master at this point.  I also could not reproduce this with v3.0.7.

My steps to test this, on macOS Catalina:

1)  Download the v3.0.7 tgz release file
2) tar -xzvf EasyRSA-3.0.7.tgz
3) ./easyrsa init-pki
4) ./easyrsa build-ca
5) answer prompts
6) Use openssl to inspect pki/ca.crt:
`ecrist@marvin:~/Downloads/EasyRSA-3.0.7-> openssl x509 -noout -text -in pki/ca.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 17655971260519749702 (0xf5069c50ebc91846)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Easy-RSA CA
        Validity
            Not Before: Sep  9 20:05:18 2020 GMT
            Not After : Sep  7 20:05:18 2030 GMT
        Subject: CN=Easy-RSA CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
...
`

Note the default value of 2048 for the public key.

7) rm -rf pki
8) cp vars.example vars
9) edit vars file, set EASYRSA_KEY_SIZE to 4096
10) init-pki, build-ca, inspect the ca.crt file with openssl:

`ecrist@marvin:~/Downloads/EasyRSA-3.0.7-> openssl x509 -noout -text -in pki/ca.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 13409044655235921465 (0xba167f11dcaff639)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=Easy-RSA CA
        Validity
            Not Before: Sep  9 20:06:10 2020 GMT
            Not After : Sep  7 20:06:10 2030 GMT
        Subject: CN=Easy-RSA CA
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (4096 bit)
...
`

I get the same result with current master.

Closing this issue.

**Closed by ecrist** 2020-09-09 20:11 UTC
Labels: bug

**Comment by tpa10** [comment] 2021-06-30 02:36
Having the exact same issue, using 3.0.8, installed via yum/rpm from the CentOS EPEL repo.
Used the command line to override keysize, algorithm, and digest.

**Comment by grizzler0031** [comment] 2021-11-22 19:54
Confirmed. The vars file is ignored unless --vars=<file spec> is used.
Version 3.0.8 on Debian Testing.

**Comment by bertvandepoel** [comment] 2023-08-20 00:38
Also still the case on 3.0.8-1ubuntu1. Has had me confused for hours what I was doing wrong.

**Comment by ecrist** [comment] 2023-08-20 01:24
We don't control the various linux distro packages. That version, v3.0.8, is quite out of date at this point.

Eric F Crist
________________________________
