### ISSUE TITLE
Asking for passphrase when not expected during build-ca

### ISSUE THREAD

**Issue by pmichali** [OpenVPN/easy-rsa#454] opened 2021-08-20 14:19 UTC
Using EasyRSA 3.0.8 and openssl 3.0.0-beta3-dev on ubuntu 20.04 system

I'm seeing two problems. When I doing build-ca, it asks for CA passphrase (expected), but then for PEM passphrase (unexpected). It "seems" like openssl is not correctly reading the passphrase on cert request via -passin file:/path/to/file (maybe a openssl issue?)

`openssl genrsa -out /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/tmp.CH89tn -aes256 -passout file:/etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/tmp.EoUeRA 2048`

Key (encrypted) and password file created...
```
ls -l /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/
total 16
-rw------- 1 root root 1874 Aug 20 08:57 tmp.CH89tn
-rw------- 1 root root    6 Aug 20 08:52 tmp.EoUeRA
```
When I do the request, it is asking for the PEM passphrase, which should have been in the above file...
```
openssl req -utf8 -new -key /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/tmp.CH89tn -keyout /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/tmp.CH89tn -out /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/tmp.kt6j18 -passin file:/etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18241.lYRAOW/tmp.EoUeRA -x509 -days 3650
Enter PEM pass phrase:
```

The second problem is that, if I use the nopass option, it still is asking for PEM passphrase...
`openssl genrsa -out /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18523.BGha1W/tmp.UNPqSl 2048`

The key (unencrypted) is created...
```
ls -l /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18523.BGha1W/
total 12
-rw------- 1 root root 1704 Aug 20 09:25 tmp.UNPqSl
```

When I do the request, I get this...
```
openssl req -utf8 -new -key /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18523.BGha1W/tmp.UNPqSl -keyout /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18523.BGha1W/tmp.UNPqSl -out /etc/easy-rsa-3.0.8/easyrsa3/pki/easy-rsa-18523.BGha1W/tmp.suFcWz -x509 -days 3650
Enter PEM pass phrase:
```

Is that correct? If I remove the -keyout arg, it proceeds without asking for any passphrase.

**Comment by schopin-pro** [comment] 2021-11-19 10:47
I can confirm that the bug exists when using OpenSSL 3.0. It's a regression that seems to have been fixed in the mainline https://github.com/openssl/openssl/commit/6b38d7dc1bccc708279ca5091ebc28cd4bdf225d

**Comment by TinCanTech** [comment] 2022-03-15 03:31
For the record: EasyRSA does **not** support OpenSSL version 3.0.0

EasyRSA will support OpenSSL 3.0.1+

**Closed by TinCanTech** 2022-03-15 03:31 UTC

**Comment by CanadianBaconBoi** [comment] 2022-08-16 03:39
Note, I am currently using openssl-1:3.0.1-30.el9 on CentOS Stream 9 and this issue is not fixed.

**Comment by bohrsty** [comment] 2022-09-17 12:51
same here, easy-rsa isn't working with openssl 3.0.5

> EasyRSA Version Information
> Version:     3.0.8
> Generated:   Wed Sep  9 15:59:45 CDT 2020
> SSL Lib:     OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
> Git Commit:  f12e00e53b4f486ce3d119ca429198780fa694ac
> Source Repo: https://github.com/OpenVPN/easy-rsa

it asks for `Enter PEM pass phrase` even if "nopass" option is given, commands "build-ca" and "build-server-full"...

**Comment by TinCanTech** [comment] 2022-09-17 15:22
@bohrsty 
> EasyRSA Version Information
> **Version: 3.0.8**
> Generated: Wed Sep 9 15:59:45 CDT 2020
> SSL Lib: **OpenSSL 3.0.5** 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)

You need either EasyRSA version `3.0.9` or `3.1.x` for OpenSSL version 3.x support.

**Comment by KadirFiratFTW** [comment] 2023-01-13 17:19
Same issue here

**Comment by TinCanTech** [comment] 2023-01-13 17:25
@KadirFiratFTW **The solution is provided**, or did you not read this issue ?

**Comment by TinCanTech** [comment] 2026-02-05 19:39
@phlibi You need to use the correct option to disable passwords. See `easyrsa help build-ca`.

**Comment by phlibi** [comment] 2026-02-06 07:52
@TinCanTech Ah, sorry, my bad. I failed to give context/details, must have been too late in the evening. The issue is not that I would want it to run without asking for a passphrase, but that it's asking for *two* passphrases ("Enter New CA Key Passphrase" by easyrsa and then again "Enter PEM pass phrase" by openssl), as described in the first paragraph of the OP:

> I'm seeing two problems. When I doing build-ca, it asks for CA passphrase (expected), but then for PEM passphrase (unexpected).

I've seen other reports of this in the web, most closely probably [Debian bug #1039014](https://bugs-devel.debian.org/cgi-bin/bugreport.cgi?bug=1039014). And then there's your own report in https://github.com/OpenVPN/easy-rsa/issues/476 Please excuse the confusion.
