### ISSUE TITLE
Error when signing

### ISSUE THREAD

**Issue by marvdias** [OpenVPN/easy-rsa#145] opened 2017-08-25 20:39 UTC
Hello everyone, I am getting an error when trying to sign 

I am doing the following:
```
$easyrsa/easyrsa3/easyrsa init-pki
$easyrsa/easyrsa3/easyrsa build-ca nopass
#needed as FPM doesn't build include empty directories in debian packages
touch pki/issued/.emptyfile
touch pki/certs_by_serial/.emptyfile
cp pki/ca.crt etage-bundle.crt

#create keys for openvpn
$easyrsa/easyrsa3/easyrsa gen-req server nopass
$easyrsa/easyrsa3/easyrsa sign server server
```
the error is:
```
ERROR: adding extensions in section default
140737153455112:error:22097082:X509 V3 routines:DO_EXT_NCONF:unknown extension name:v3_conf.c:125:
140737153455112:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=copy_extensions, value=copy

Easy-RSA error:

signing failed (openssl output above may have more detail)
```
What should I do? Any thoughts?

**Comment by Allfd** [comment] 2017-08-25 22:09
Same issue, also on debian.

**Comment by ecrist** [comment] 2017-08-26 03:45
This is likely a bug introduced recently in my attempt to fill a feature request. I'll look into it in the morning. 

Eric Crist

**Comment by petersm1** [comment] 2017-08-28 12:49
I have it to , and we hope for a fix :-)
`Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
ERROR: adding extensions in section default
47430495403544:error:22097082:X509 V3 routines:DO_EXT_NCONF:unknown extension name:v3_conf.c:125:
47430495403544:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=copy_extensions, value=copy

Easy-RSA error:

signing failed (openssl output above may have more detail)

**Comment by chaserhkj** [comment] 2017-08-28 14:54
Seems to be a duplicate of #141

**Comment by yannw** [comment] 2017-08-29 15:40
same issue with signing here.
openssl version: 1.0.2g

**Comment by dahrens** [comment] 2017-08-29 17:36
I can also confirm this bug on ubuntu 16.04 LTS using version 3.2.1 - Your assumption that it was introduced recently seems correct as downgrading to 3.2.0 fixes the issue for me.

**Comment by ecrist** [comment] 2017-08-29 21:22
There is no 3.2.x version, only 3.0.x. 

Eric Crist

**Comment by dahrens** [comment] 2017-08-30 08:39
Thats interesting. I followed the instructions in (the building docs)[https://github.com/OpenVPN/easy-rsa/blob/master/build/Building.md] and i really changed the mentioned version into '3.2.0' and it works now.

**Comment by djsly** [comment] 2017-09-01 16:53
Same issue here. when using a version from master.

**Comment by ecrist** [comment] 2017-09-02 14:32
I've tested v3.0.3 on both a Mac and a FreeBSD system and I'm not seeing any errors.  I suspect this is a problem with either Debian, or the package created by the Debian distro maintainer.

On my Mac (0.9.8zh)
```
ecrist@meow:~/easy-rsa-test/EasyRSA-3.0.3-> ./easyrsa init-pki

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki

ecrist@meow:~/easy-rsa-test/EasyRSA-3.0.3-> ./easyrsa build-ca nopass
Generating a 2048 bit RSA private key
...............................................................................................................................+++
.......+++
writing new private key to '/Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki/private/ca.key.pnnHCJPIUv'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:foobar

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki/ca.crt

ecrist@meow:~/easy-rsa-test/EasyRSA-3.0.3-> ./easyrsa gen-req server nopass
Generating a 2048 bit RSA private key
.......+++
..............+++
writing new private key to '/Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki/private/server.key.LE2G8qcxyS'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [server]:

Keypair and certificate request completed. Your files are:
req: /Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki/reqs/server.req
key: /Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki/private/server.key

ecrist@meow:~/easy-rsa-test/EasyRSA-3.0.3-> ./easyrsa sign server server


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate for 3650 days:

subject=
    commonName                = server


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
Using configuration from ./openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Aug 31 14:26:45 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Certificate created at: /Users/ecrist/easy-rsa-test/EasyRSA-3.0.3/pki/issued/server.crt
```

On FreeBSD (OpenSSL 1.0.1s):
```
ecrist@terrance:~/EasyRSA-3.0.3-> ./easyrsa init-pki

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /home/ecrist/EasyRSA-3.0.3/pki

ecrist@terrance:~/EasyRSA-3.0.3-> ./easyrsa build-ca nopass
Generating a 2048 bit RSA private key
.....+++
.+++
writing new private key to '/home/ecrist/EasyRSA-3.0.3/pki/private/ca.key.pHpNzKYzZC'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [Easy-RSA CA]:foobar

CA creation complete and you may now import and sign cert requests.
Your new CA certificate file for publishing is at:
/home/ecrist/EasyRSA-3.0.3/pki/ca.crt

ecrist@terrance:~/EasyRSA-3.0.3-> ./easyrsa gen-req server nopass
Generating a 2048 bit RSA private key
........+++
...........................+++
writing new private key to '/home/ecrist/EasyRSA-3.0.3/pki/private/server.key.pPC0pkoKXW'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Common Name (eg: your user, host, or server name) [server]:

Keypair and certificate request completed. Your files are:
req: /home/ecrist/EasyRSA-3.0.3/pki/reqs/server.req
key: /home/ecrist/EasyRSA-3.0.3/pki/private/server.key

ecrist@terrance:~/EasyRSA-3.0.3-> ./easyrsa sign server server


You are about to sign the following certificate.
Please check over the details shown below for accuracy. Note that this request
has not been cryptographically verified. Please be sure it came from a trusted
source or that you have verified the request checksum with the sender.

Request subject, to be signed as a server certificate for 3650 days:

subject=
    commonName                = server


Type the word 'yes' to continue, or any other input to abort.
  Confirm request details: yes
./easyrsa: [[: not found
Using configuration from ./openssl-1.0.cnf
Check that the request matches the signature
Signature ok
The Subject's Distinguished Name is as follows
commonName            :ASN.1 12:'server'
Certificate is to be certified until Aug 31 14:35:22 2027 GMT (3650 days)

Write out database with 1 new entries
Data Base Updated

Certificate created at: /home/ecrist/EasyRSA-3.0.3/pki/issued/server.crt
```

**Closed by ecrist** 2017-09-02 14:32 UTC

**Comment by bablat** [comment] 2018-01-10 22:56
Unfortunately, this still happens on my build. Exact same issue when trying to sign server certificates.

I'm using latest master easy-rsa, OpenVPN 2.4.4 x86_64-pc-linux-gnu (latest stable Xenial) and Ubuntu 16.04 LTS.

**Comment by TinCanTech** [comment] 2018-01-11 12:26
@bablat Master is not suitable for production usage, please use version 3.0.4 or one of the official releases (currently 3.0.3).

**Comment by bablat** [comment] 2018-01-11 13:35
@TinCanTech, I tried both 3.0.3 and 3.0.4, both had the same issue so I had to dive in and debug sh (which is something I managed to avoid in 10 years...).

Turns out easyrsa didn't expect me to have a space in my folder structure... $req_in may contain spaces, take a look at 660.

Moved to a space-less directory, all is well now. Thanks for your work on this project!

**Comment by TinCanTech** [comment] 2018-01-11 14:05
where did you have a space in your folder names ?

**Comment by ecrist** [comment] 2018-01-11 14:14
Can you try and use 3.0.4 branch?

Eric Crist

**Comment by bablat** [comment] 2018-01-11 14:39
@ecrist As I wrote above, I tried master, v3.0.3, v3.0.4. All had this issue.
I had a directory name containing a space somewhere up the tree, should be easy to reproduce:
e.g. clone easy-rsa into "/tmp/some folder containing a space/easy-rsa" and try to sign a server-type request.

**Comment by vinifr** [comment] 2022-02-12 23:49
Still same problem in 3.0.4 or 3.0.8 under Debian 10. In my case, it looks like the commonName is corrupted.

_./easyrsa sign-req server server

Note: using Easy-RSA configuration from: ./vars

Request subject, to be signed as a server certificate for 3650 days:

subject=
    commonName                = \0D_

I was expecting commonName = server. Request file is into EasyRSA-3.0.4/pki/reqs/
